version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:stable
    network_mode: bridge
    ports:
      - "8124:8123"
    # UI at default port 8123
    privileged: true
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/media
      - /dev:/dev
      - /run/dbus:/run/dbus:ro