services:
  matter-hub:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    restart: unless-stopped
    network_mode: host
    environment: # more options can be found in the configuration section
      - HAMH_HOME_ASSISTANT_URL=http://192.168.1.100:8123/
      - HAMH_HOME_ASSISTANT_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkMjlmODI0NGZkMjk0OGNiOGY4NzA2M2ViMWYxODhlMyIsImlhdCI6MTc1OTA4MDgyMCwiZXhwIjoyMDc0NDQwODIwfQ.qqBMGdLk4NEQ6sHqS_IqbcxEg_VfAn5jpT7yCEjefxg
      - HAMH_LOG_LEVEL=info
      - HAMH_HTTP_PORT=8482
    volumes:
      - $PWD/home-assistant-matter-hub:/data