version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: chromium_chromium_1
      APP_PORT: 3000

  chromium:
    image: jlesage/firefox:v1.18.0
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/config
    shm_size: "1gb"
    restart: on-failure